nelmio_api_doc:
    documentation:
        info:
            title: API документация
            description:
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1
