version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:8.2.2
    init: true
    environment:
      - node.name=catalog_es1
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ELASTIC_PASSWORD=123123"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/log/:/usr/share/elasticsearch/logs
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '127.0.0.1:9200:9200'
    networks:
      - LAMP

  kibana:
    image: kibana:8.2.2
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL="http://localhost:9200"
      - server.host=127.0.0.1
    networks:
      - LAMP
    ports:
      - "5601:5601"

volumes:
  db-data:

networks:
  LAMP:
    name: LAMP
