controllers:
    resource: ../src/Controller/
    type: attribute

#TODO поправить пути
admin_controllers:
    resource: c:/work/avy/src/Controller/Admin/
    prefix: "/admin"

a-flow_controllers:
    resource: c:/work/avy/src/Controller/Domains/A_flow/
    host: "a-flow.%main_domain%"

hy-lock_controllers:
    resource: c:/work/avy/src/Controller/Domains/Hy_lock/
    host: "hy-lock.%main_domain%"